version: '3.7'

services:

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 127.0.0.1:3306:3306

  ttn:
    build:
      context: ./ttn
    image: klax_ttn:local
    container_name: klax_ttn
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      PATH_LOG: ${PATH_LOG}
      LOG_FILE: ${LOG_FILE}
      LOG_LEVEL: ${LOG_LEVEL}
      TIMEZONE: ${TIMEZONE}
    volumes:
      - ${PATH_LOG}:/var/opt/app/log
    depends_on:
      - mariadb

  api:
    build:
      context: ./api
    image: klax_api:local
    container_name: klax_api
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SCHEMA: ${MYSQL_SCHEMA}
      PATH_LOG: ${PATH_LOG}
      LOG_FILE: ${LOG_FILE}
      LOG_LEVEL: ${LOG_LEVEL}
      TIMEZONE: ${TIMEZONE}
      FORWARDED_ALLOW_IPS: ${FORWARDED_ALLOW_IPS}
      SECRET: ${SECRET}
    volumes:
      - ${PATH_LOG}:/var/opt/app/log
    depends_on:
      - mariadb
      - ttn
